from queries import *
import pandas as pd
import os
from dotenv import load_dotenv
import google.generativeai as genai


# --------------------------------------------------
# Query Map
# --------------------------------------------------

query_map = {

    "TOTAL_REVENUE": {
        "sql": TOTAL_REVENUE,
        "description": "Total revenue based on payment value."
    },

    "TOTAL_ORDERS": {
        "sql": TOTAL_ORDERS,
        "description": "Total number of orders."
    },

    "TOTAL_CUSTOMERS": {
        "sql": TOTAL_CUSTOMERS,
        "description": "Total number of customers."
    },

    "TOTAL_PRODUCTS": {
        "sql": TOTAL_PRODUCTS,
        "description": "Total number of unique products."
    },

    "TOTAL_SELLERS": {
        "sql": TOTAL_SELLERS,
        "description": "Total number of unique sellers."
    },

    "AVERAGE_ORDER_VALUE": {
        "sql": AVERAGE_ORDER_VALUE,
        "description": "Average amount spent per order."
    },

    "AVERAGE_RATING": {
        "sql": AVERAGE_RATING,
        "description": "Average customer review rating."
    },

    "AVERAGE_PRODUCT_PRICE": {
        "sql": AVERAGE_PRODUCT_PRICE,
        "description": "Average selling price of products based on order items."
    },

    "AVERAGE_DELIVERY_DAYS": {
        "sql": AVERAGE_DELIVERY_DAYS,
        "description": "Average number of days between order purchase and customer delivery."
    },

    "MONTHLY_REVENUE": {
        "sql": MONTHLY_REVENUE,
        "description": "Revenue generated for each month based on payment value."
    },

    "TOP_PRODUCT_CATEGORIES": {
        "sql": TOP_PRODUCT_CATEGORIES,
        "description": "Top product categories ranked by sales value based on item price."
    },

    "TOP_CATEGORY_SALES": {
        "sql": TOP_CATEGORY_SALES,
        "description": "Top product categories ranked by total item sales value."
    },

    "PAYMENT_METHOD": {
        "sql": PAYMENT_METHOD,
        "description": "Number of unique orders for each payment method."
    },

    "REVENUE_BY_STATE": {
        "sql": REVENUE_BY_STATE,
        "description": "Total payment revenue generated by each customer state."
    },

    "CUSTOMERS_BY_STATE": {
        "sql": CUSTOMERS_BY_STATE,
        "description": "Number of customers in each state."
    },

    "CUSTOMER_GROWTH": {
        "sql": CUSTOMER_GROWTH,
        "description": "Number of unique customers recorded for each month."
    },

    "TOP_CITIES": {
        "sql": TOP_CITIES,
        "description": "Top cities ranked by number of customers."
    },

    "NEW_RETURNING_CUSTOMERS": {
        "sql": NEW_RETURNING_CUSTOMERS,
        "description": "Number of customers classified as new or returning based on their number of orders."
    },

    "ORDER_STATUS": {
        "sql": ORDER_STATUS,
        "description": "Number of orders for each order status."
    },

    "REVIEW_SCORE": {
        "sql": REVIEW_SCORE,
        "description": "Distribution of customer review scores."
    },

    "MONTHLY_REVIEWS": {
        "sql": MONTHLY_REVIEWS,
        "description": "Average customer review rating for each month."
    },

    "DELIVERY_PERFORMANCE": {
        "sql": DELIVERY_PERFORMANCE,
        "description": "Number of delivered orders classified as on time or late."
    },

    "PRICE_RANGE": {
        "sql": PRICE_RANGE,
        "description": "Number of unique products in each product price range."
    },

    "AVERAGE_PRICE_BY_CATEGORY": {
        "sql": AVERAGE_PRICE_BY_CATEGORY,
        "description": "Average transactional selling price for each product category."
    },
}

# --------------------------------------------------
# Gemini Configuration
# --------------------------------------------------

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")

genai.configure(api_key=api_key)

model = genai.GenerativeModel("gemini-2.5-flash")


# --------------------------------------------------
# Identify Query
# --------------------------------------------------

def identify_query(question):

    try:
        available_queries = "\n".join(
            [
                f"{name} - {details['description']}"
                for name, details in query_map.items()
            ]
        )

        prompt = f"""
You are an assistant that selects the most suitable SQL query
for a business analytics question.

Available Queries:

{available_queries}

User Question:
{question}

Rules:
- Select the query that best matches the user's question.
- Return ONLY the query name.
- Do not explain your answer.
- Do not use markdown.
"""

        response = model.generate_content(prompt)

        if not response.text:
            return None

        query_name = response.text.strip().upper()

        if query_name in query_map:
            return query_name

        return None

    except Exception as e:
        print(f"Query identification error: {e}")
        return None


# --------------------------------------------------
# Execute Query
# --------------------------------------------------

def execute_query(query_name, conn):

    try:
        if query_name is None:
            return None

        sql = query_map[query_name]["sql"]

        return pd.read_sql(sql, conn)

    except Exception as e:
        print(f"SQL execution error: {e}")
        return None

# --------------------------------------------------
# Explain Result
# --------------------------------------------------

def explain_result(question, query_name, df):

    try:
        if query_name is None:
            return "Sorry, I couldn't understand that question."

        description = query_map[query_name]["description"]

        prompt = f"""
You are an experienced Business Data Analyst.

User Question:
{question}

Meaning of the SQL result:
{description}

SQL Result:

{df.to_string(index=False)}

Explain the answer in simple business English.

Important:
- Use the meaning of the SQL result correctly.
- Do not call unique orders "transactions" unless the data actually represents transactions.
- Do not invent information that is not present in the result.
- Mention the important values from the result.
- Keep the answer under 150 words.
- End with one useful business recommendation.
"""

        response = model.generate_content(prompt)

        if not response.text:
            return "The data was retrieved successfully, but I couldn't generate an explanation."

        return response.text

    except Exception as e:
        print(f"AI explanation error: {e}")
        return "The data was retrieved successfully, but I couldn't generate an AI explanation."

# --------------------------------------------------
# Main AI Function
# --------------------------------------------------

def ask_ai(question, conn):

    query_name = identify_query(question)

    if query_name is None:
        return "Sorry, I couldn't understand that question.", None

    df = execute_query(query_name, conn)

    if df is None:
        return "I couldn't retrieve the required data. Please try again.", None

    answer = explain_result(question, query_name, df)

    return answer, df